Repository nestjs/nest-cli, pull requests merged in 2018-06, with the labels that each got.

#140 fix(new): --skip-install never working (sprint-1)
  actions/new.action.ts
  commands/generate.command.ts
  commands/new.command.ts
  commands/update.command.ts
  lib/inputs/parse.ts
  test/lib/inputs/parse.spec.ts
Labels: bug, enhancement

#151 fix(new): format install directory to match schematic directory
  actions/new.action.ts
Labels: bug, critic

#156 feature(gitignore) : add gitignore file
  lib/package-managers/index.ts
  package-lock.json
  package.json
  test/lib/package-managers/npm.package-manager.spec.ts
  test/lib/package-managers/yarn.package-manager.spec.ts
Labels: feature, minor
