Repository nestjs/nest-cli, pull requests merged in 2018-09, with the labels that each got.

#167 Fixed: Create project crash
  lib/package-managers/abstract.package-manager.ts
Labels: bug

#176 refactor: use nest-cli.json (backward compatible + defaults)
  lib/configuration/defaults.ts
  lib/configuration/nest-configuration.loader.ts
  lib/readers/file-system.reader.ts
  lib/readers/reader.ts
  test/lib/configuration/nest-configuration.loader.spec.ts
Labels: improvement

#185 feature: add sourceRoot option
  actions/generate.action.ts
  lib/configuration/configuration.ts
  lib/configuration/defaults.ts
  lib/configuration/nest-configuration.loader.ts
  lib/dependency-managers/nest.dependency-manager.ts
  package.json
  test/lib/configuration/nest-configuration.loader.spec.ts
Labels: feature, improvement
