Repository nestjs/nest-cli, pull requests merged in 2024-11, with the labels that each got.

#2800 fix: webpack default config - IgnorePlugin
  lib/compiler/defaults/webpack-defaults.ts
Labels: improvement

#2792 fix: show type check warning only when builder is not swc
  actions/build.action.ts
  commands/build.command.ts
  commands/start.command.ts
Labels: bug

#2769 feat!: drop uncommon variants of nest cli config file name
  lib/configuration/nest-configuration.loader.ts
  test/lib/configuration/nest-configuration.loader.spec.ts
Labels: improvement, breaking

#2718 Chore/upgrade inquirer package
  actions/new.action.ts
  lib/questions/questions.ts
  lib/ui/messages.ts
  lib/utils/project-utils.ts
  package-lock.json
  package.json
  test/lib/questions/questions.spec.ts
Labels: dependencies, breaking

#2312 #2026 feat: nest build --all flag
  actions/build.action.ts
  commands/build.command.ts
  lib/compiler/assets-manager.ts
  lib/compiler/compiler.ts
  lib/compiler/helpers/delete-out-dir.ts
  lib/compiler/helpers/get-builder.ts
  lib/compiler/helpers/get-tsc-config.path.ts
  lib/compiler/helpers/get-webpack-config-path.ts
  lib/compiler/swc/swc-compiler.ts
  lib/compiler/watch-compiler.ts
  lib/compiler/webpack-compiler.ts
Labels: feature

#2096 feat(schematics): list schematics from extended collections
  lib/schematics/custom.collection.ts
  test/jest-config.json
  test/lib/schematics/custom.collection.spec.ts
  test/lib/schematics/fixtures/extended/collection.json
  test/lib/schematics/fixtures/package/a/b/c/collection.json
  test/lib/schematics/fixtures/package/index.js
  test/lib/schematics/fixtures/package/package.json
  test/lib/schematics/fixtures/simple/collection.json
Labels: feature

#2522 feat: add flag to disable shell mode for `nest start --watch`
  actions/start.action.ts
  commands/start.command.ts
Labels: feature

#2818 feat: add support for --env-file flag
  actions/start.action.ts
  commands/start.command.ts
Labels: improvement
