Repository nestjs/nest-cli, pull requests merged in 2024-07, with the labels that each got.

#2526 refactor: replace `shelljs` usage with `fs` methods
  lib/compiler/assets-manager.ts
  package-lock.json
  package.json
Labels: refactor

#2553 Fix assets copying
  lib/compiler/assets-manager.ts
Labels: bug

#2630 feat: replace 'source-map-support' with nodejs native source mapping binding
  actions/start.action.ts
  package-lock.json
  package.json
Labels: improvement

#2627 fix: propagate errors raised when loading the webpack configuration file
  actions/build.action.ts
  lib/compiler/assets-manager.ts
  lib/utils/is-module-available.ts
Labels: improvement
